### ISSUE TITLE
Hang-punctuation

### ISSUE THREAD

**Issue by AspirationYC** [AspirationYC/content-page#1]
Hi @hellachella,

How do I fix the hang-punctuation? It is collapsing to the next paragraph. Also, the hang-punctuation only goes on `blockquote` right?

<img width="563" alt="hang-punc issue" src="https://user-images.githubusercontent.com/31771017/36497958-e38a815a-170a-11e8-921f-9449f6017f03.png">

**Comment by hellachella** [comment]
Wrap only the ` "` character in a span: 

`<p><span class="hang-punc>“</span>Who invited you aboard?”</p>`
